project:
  type: website

website:
  title: "hrishit chaudhuri"
  navbar:
    right:
      - href: index.qmd
        text: about
      - href: resume.pdf
        text: cv

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



